version: '3.8'

services:
  backend:
    build:
      context: ./Back/ReservationAPI
      dockerfile: Dockerfile
    container_name: reservation-api
    volumes:
      - ./Back/ReservationAPI:/var/www
      - ./Back/ReservationAPI/database:/var/www/database
      - /var/www/vendor
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
    # Le command est maintenant géré par l'ENTRYPOINT du Dockerfile ou peut être surchargé ici
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./Front/ReservationFront
      dockerfile: Dockerfile
    container_name: reservation-front
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./Front/ReservationFront/nginx.conf:/etc/nginx/conf.d/default.conf:ro
