version: '3.8'

services:
  backend:
    build:
      context: ./Back/ReservationAPI
      dockerfile: Dockerfile
    container_name: reservation-api
    volumes:
      - ./Back/ReservationAPI:/var/www
      - ./Back/ReservationAPI/database:/var/www/database
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_KEY=base64:PVREeK9vXfL7bX8/D8J7u0/6/jL5mE8/K9vXfL7bX8= # À changer par votre clé
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./Front/ReservationFront
      dockerfile: Dockerfile
    container_name: reservation-front
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./Front/ReservationFront/nginx.conf:/etc/nginx/conf.d/default.conf:ro
